language: c++
before_script: "./configure"
script: "make"
branches:
  only:
    - master
notifications:
  recipients:
    - jamie@lacewing-project.org
  email:
    on_success: change
    on_failure: always



